USE DENTISTA;
SELECT * FROM DENTIST;

INSERT INTO DENTIST(DENTIST_Fname, DENTIST_LNAME, DENTIST_EMAIL, DENTIST_PASSWORD, DENTIST_PHONE_NUMBER, DENTIST_ADDRESS, DENTIST_ZIP_CODE, DENTIST_REGION, DENTIST_CITY, DENTIST_CREDIT_CARD_NUMBER, DENTIST_IMAGE_URL)
VALUES ('Yousef', 'Gamal', 'yousef.gamal.it@gmail.com', 'y2o9u5s2e0f00', '01128396620', 'Maadi', '11716', 'Maadi', 'Cairo', '4152-2222-3334-1111', 'EMPTY');

UPDATE DENTIST SET DENTIST_IMAGE_URL = "https://miro.medium.com/max/800/1*jQFE4nKOYj8J5TMgj8RxIw.jpeg" WHERE DENTIST_EMAIL = "yousef.gamal.it@gmail.com";

INSERT INTO DENTIST(DENTIST_Fname, DENTIST_LNAME, DENTIST_EMAIL, DENTIST_PASSWORD, DENTIST_PHONE_NUMBER, DENTIST_ADDRESS, DENTIST_ZIP_CODE, DENTIST_REGION, DENTIST_CITY, DENTIST_CREDIT_CARD_NUMBER, DENTIST_IMAGE_URL)
VALUES ('Ahmed', 'Ihab', 'Ahmed.Ihab.it13@gmail.com', 'y2o9u5s2e0f00', '01128396621', 'Maadi', '11716', 'Maadi', 'Cairo', '4152-2222-3334-1111', 'EMPTY');

SELECT * FROM DENTIST LIMIT 3, 1;

INSERT INTO CATEGORY(CATEGORY_NAME, CATEGORY_DESCRIPTION) VALUES ("DENTICAL CHAIRS", "VERY COMFORTABLE CHAIRS");




INSERT INTO PRODUCT(PRODUCT_NAME, CATEGORY, BRAND, DESCRIPTION, PRICE, SELLING_PRICE, IMAGE_URL, Number_of_Units)
VALUES ("DENTICAL 2 CHAIR", "Chairs", "ZARA", "A COMFORTABLE 2 CHAIR", 200, 450, "https://bloximages.chicago2.vip.townnews.com/napavalleyregister.com/content/tncms/assets/v3/editorial/f/37/f378ae96-b89b-5ccd-8dbf-3b12656419f4/5d23a7253d9d5.image.jpg?crop=1174%2C1174%2C295%2C0&resize=1200%2C1200&order=crop%2Cresize", 10);


INSERT INTO CATEGORY(CATEGORY_NAME, CATEGORY_DESCRIPTION) VALUES ("PlayStation", "VERY COMFORTABLE Game");

INSERT INTO PRODUCT(PRODUCT_NAME, CATEGORY, BRAND, DESCRIPTION, PRICE, TOTAL_PRICE, SELLING_PRICE, IMAGE_URL)
VALUES ("Playstation 5", "video game", "ZARA", "Amazing Game", 29000, 250, 450, "https://sony-playstation-store.com/wp-content/uploads/2013/06/143354-games-feature-sony-playstation-5-release-date-rumours-and-everything-you-need-to-know-about-ps5-image1-cvz3adase9.jpg");



INSERT INTO PRODUCT(PRODUCT_NAME, CATEGORY, BRAND, DESCRIPTION, PRICE, SELLING_PRICE, SELLING_PRICE, IMAGE_URL)
VALUES ("Playstation 4", "video game", "SONY", "Amazing Game", 9000, 250, 450, "https://i.pcmag.com/imagery/reviews/04JwgIpLICJujPxYZvmtdBn-4..1569481805.jpg");


SELECT * FROM DENTIST;

SELECT * FROM PRODUCT;

UPDATE DentistCart SET Number_Units = 2 WHERE DENTIST_ID = 3 and PRODUCT_ID = 2;


SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, BRAND, DESCRIPTION, PRICE, IMAGE_URL FROM PRODUCT  LIMIT 2, 1;
SELECT * FROM PRODUCT WHERE MATCH(PRODUCT_NAME) AGAINST ('Playstation' IN natural language mode)  ORDER BY MATCH(PRODUCT_NAME) AGAINST('playstation') DESC;
UPDATE DENTIST SET DENTIST_IMAGE_URL = "https://transformradiology.com/wp-content/uploads/2019/08/Andrew-Ng_headshot-web.jpg" WHERE DENTIST_EMAIL = "yousef.gamal.it@gmail.com";

SELECT * FROM DentistCart;
DROP TABLE DentistCart;
CREATE TABLE DentistCart(
DENTIST_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
Number_Units INT,
foreign key (DENTIST_ID) references DENTIST(DENTIST_ID) ON delete cascade ON update Cascade,
foreign key (PRODUCT_ID) references PRODUCT(Product_ID) ON delete cascade ON update Cascade
);

drop table dentist_likes;
drop table dentist_comment;

SELECT * FROM DENTIST_COMMENT;

CREATE TABLE DENTIST_COMMENT(
COMMENT_ID INT NOT NULL PRIMARY KEY auto_increment,
DENTIST_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL, 
COMMENT_CONTEXT LONGTEXT NOT NULL,
COMMENT_TIME datetime,
LIKES INT,
foreign key(PRODUCT_ID) references PRODUCT(PRODUCT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
foreign key(DENTIST_ID) references DENTIST(DENTIST_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DENTIST_LIKES(
DENTIST_ID INT NOT NULL,
COMMENT_ID INT NOT NULL,
FOREIGN KEY(DENTIST_ID) references DENTIST(DENTIST_ID) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(COMMENT_ID) references DENTIST_COMMENT(COMMENT_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

USE DENTISTA;
DROP TABLE STORE_PRODUCT;
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT
(
  PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
  PRODUCT_NAME VARCHAR(255) NOT NULL,
  PRICE INT NOT NULL,
  SELLING_PRICE INT NOT NULL,
  IMAGE_URL VARCHAR(255) ,
  NUMBER_OF_UNITS INT NOT NULL,
  STORE_ID INT NOT NULL,
  RATE INT,
  NO_OF_REVIEWERS INT,
  CATEGORY VARCHAR(255),
  PRIMARY KEY (PRODUCT_ID),
  foreign key (STORE_ID) references STORE(STORE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
