CREATE OR REPLACE VIEW LOGIN_DATA(Email, Password, AccountType) AS SELECT DENTIST_EMAIL , DENTIST_PASSWORD, "Dentist"  FROM DENTIST DENT 
union ALL 
SELECT EMAIL, PASSWORD, "Store" FROM STORE ST
UNION ALL
SELECT MANAGER_EMAIL, MANAGER_PASSWORD, "Manager" FROM MANAGER MNG 
UNION ALL
SELECT DELIVERY_EMAIL, DELIVERY_PASSWORD, "Delivery" FROM DELIVERY DLV;

alter table delivery add Delivery_PHONE_NUMBER VARCHAR(15) NOT NULL;